#tomcat port
server:
  port: 9001
 
#jsp
spring:
  mvc:
    view:
      prefix: /WEB-INF/market/
      suffix: .jsp
  devtools:
    livereload:
      enabled: true

#mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dragon?serverTimezone=Asia/Seoul
    username: root
    password: 1234

#mybatis
mybatis:
  type-aliases-package: boot.data.mapper,boot.data.dto #boot.data.*해도 됨
  mapper-locations:
  - /mapper/**/*.xml