#tomcat port
server:
  port: 8090
  
#jsp
spring:
  mvc:
    view:
      prefix: /WEB-INF/
      suffix: .jsp
  devtools:
    livereload:
      enabled: true
      
#mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dragon?serverTimezone=Asia/Seoul
    username: root
    password: 1234
    
#mybatis
mybatis:
  type-aliases-package: boot.quiz.book,boot.quiz.bookstore
  mapper-locations:
  - /mapper/**/*.xml
